export const HANDLE_FOCUS = "HANDLE_FOCUS";
export const HANDLE_BLUR = "HANDLE_BLUR";
export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";

export const SELECT_ITEM = "SELECT_ITEM";
export const UPDATE_ITEMS = "UPDATE_ITEMS";

export const LOAD_ITEMS_REQUEST = "LOAD_ITEMS_REQUEST";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const LOAD_ITEMS_FAIL = "LOAD_ITEMS_FAIL";

export const VALIDATION_ERROR = "VALIDATION_ERROR";
export const CLOSE_POPOVER = "CLOSE_POPOVER";
