export const LOAD_ITEMS_REQUEST = "LOAD_ITEMS_REQUEST";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const LOAD_ITEMS_FAIL = "LOAD_ITEMS_FAIL";

export const QUERY_CHANGED = "QUERY_CHANGED";
export const VALUE_CHANGED = "VALUE_CHANGED";
export const FOCUS = "FOCUS";
export const BLUR = "BLUR";
export const CLOSE_POPOVER = "CLOSE_POPOVER";
